# Generated by Django 6.0.2 on 2026-02-12 13:11

from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modelsearch", "0003_add_text_fields"),
    ]

    if connection.vendor == "postgresql":
        operations = [
            migrations.RenameIndex(
                model_name="indexentry",
                new_name="modelsearch_autocom_ea8581_gin",
                old_name="modelsear_autocom_476c89_gin",
            ),
            migrations.RenameIndex(
                model_name="indexentry",
                new_name="modelsearch_title_e31adb_gin",
                old_name="modelsear_title_9caae0_gin",
            ),
            migrations.RenameIndex(
                model_name="indexentry",
                new_name="modelsearch_body_61c094_gin",
                old_name="modelsear_body_90c85d_gin",
            ),
        ]
    else:
        operations = []
